### PR TITLE
Use fullname instead of name to name resource

### PR DESCRIPTION
**Pull request by yellowhat**
Closes: https://github.com/sustainable-computing-io/kepler-helm-chart/issues/67

### CODE REVIEW

**Review by petewall — APPROVED** [review]
Amazing! This looks great!

**Comment by yellowhat** [comment]
@rootfs
@jiangphcn

**Comment by yellowhat** [comment]
@petewall do you know how to contact @rootfs and @jiangphcn to approve?

**Comment by petewall** [comment]
Sorry I don't.

**Review by bradmccoydev — APPROVED** [review]

**Pull request merged**
