### PR TITLE
remove unused options, expose options

### PR DESCRIPTION
**Pull request by yellowhat**
This PR:
- remove unused options in the `values.yaml`
- use the templated `serviceAccountName`
- expose `resources` in the `values.yaml`
- expose `podAnnotations` in the `values.yaml`
- expose `affinity` in `values.yaml`
- expose `tolerations` in `values.yaml`

### CODE REVIEW

**Review by jiangphcn — APPROVED** [review]
LGTM

**Comment by yellowhat** [comment]
Hi, may I ask for another approval?

Thanks

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
@yellowhat can you check the CI error and fix it?

**Comment by yellowhat** [comment]
Could you try now?

**Comment by rootfs** [comment]
@yellowhat thank you!

**Comment by jiangphcn** [comment]
@yellowhat thank you!

**Pull request merged**
