### PR TITLE
avoid use specific hash to avoid too many changes in CI file

### PR DESCRIPTION
**Pull request by SamYuan1990**

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@rootfs , @bradmccoydev , in my point of view please don't use specific hash for github action.

**Comment by rootfs** [comment]
This is already discussed here https://github.com/sustainable-computing-io/kepler-helm-chart/pull/15#discussion_r1181237313
@bradmccoydev

**Comment by bradmccoydev** [comment]
Hi, @SamYuan1990 I do see where you are coming from for the action. If the testing is going to break more because we need constant fast updates and have to keep updating the version in tests then maybe this slows us down.  Since this is our own action we don't need to be concerned about pinning it for security so therefore I can change it back to main.

Can I propose that we will do a version of the action (but still point to main in the helm chart) so that one day if it breaks the other way we can roll back the version easily until it's fixed? As discussed here: https://github.com/sustainable-computing-io/kepler-action/issues/34

In the OpenSSF best practices it does state semantic versioning and versioning in repos that we have to try and adhere to the best of our ability as a sandbox project, even tho I understand that pinning to main works fine with no version internally. From the outside, it may seem a bad practice.

I'm happy to do whatever you want and can change just thought I would give reasoning behind my thoughts. I hope it makes sense.

Please let me know what you's want to do and i will adjust. Thanks

**Comment by bradmccoydev** [comment]
Also, some evidence to the rationale about pinning commits to other people's actions is that when you pin the action to a sha, it, therefore, cant be changed, it is immutable. for tags in an action, others can also push security vulnerabilities to the tag and then when you run the action it picks up the latest code in that tag. Examples of how other open source projects adopt this best practice is chainguard for example leaders in security and most of them behind openssf. https://github.com/chainguard-dev/actions/blob/main/.github/workflows/test-gitsign.yaml They pin all of their actions to shas for this reason. So the change to the external actions I dont understand, but the internal one yes

**Comment by SamYuan1990** [comment]
ref to https://github.com/sustainable-computing-io/kepler-action/issues/34#issuecomment-1525536976

DO NOT FORMALISM!

@rootfs , @bradmccoydev before we make any decisions for tag or not:
1. our CI env currently hardly depends on github agent. Which means once there any updates from GHA. In past 3/6 months, we have to adjust 2 times, according to github agent updates. Hence considering with github agent release cycle, we are not robust enough to have a tag today. 
2. as I said in https://github.com/sustainable-computing-io/kepler-action/issues/34, the reason we use main branch is that once we fixed in our action repo, we don't need to change others. 
3. or at least, we should following a tag instead of a specific hash. I don't get the points base on the fact....

with example as here, the specific commit hash base on github action agent VM/container at 2022 Dec... and some update happened with github action agent at May 1st 2023... which means some code with the specific commit hash is never workable.

Hence, 1st forget about specific hash. it's doesn't works for our action. 2nd, OpenSSF accepts with specific reason. We just edit the OpenSSF form and update with our reason.

In my point of view, it's not necessary and increasing unnecessary workload for us today. As why this PR happen and rest of our other CI benefits from the so called "bad practice" from outside. The "good practice" means this kind of PR through all repos for us.

If your guys really wants OpenSSF tag. 
1. tag our internal action
1. @rootfs, maintain the tag for all CIs at organziation level.
1. changes all the CI from `@main` to `@{{env.tag}}`

which means in comming conflicts with github action new release, we should fix in kepler-action, new tag, and update org level env...
well, in fact, if we use "bad prctice", we just update kepler-action main branch will be enough.
I suppose internal CI should skip from OpenSSF rule, as internal CI is not our code dependency and not a part of SBOM isn't it?

**Comment by SamYuan1990** [comment]
> This is already discussed here [#15 (comment)](https://github.com/sustainable-computing-io/kepler-helm-chart/pull/15#discussion_r1181237313) @bradmccoydev

see my comments at https://github.com/sustainable-computing-io/kepler-helm-chart/pull/15#discussion_r1199683674 @rootfs , @bradmccoydev , @yellowhat

**Comment by SamYuan1990** [comment]
+ Arnaud Le Hors from https://openssf.org/about/tac/ here.
@lehors
I hope you can help us with the case for OpenSSF usage. Here some questions as summary below, if you don't want to go through all the back ground:
1. in a specific program's CI, if they follow up with github action and use some 3rd party action for example `uses: actions/setup-go@v3`, will `actions/setup-go` been a part of SBOM? is there any different from `uses: actions/setup-go@v3`/`uses: actions/setup-go@main` from OpenSSF point of view?

2. for a group of repos, maintainers may found some common part of code which just for CI/CD usage. For example, set up environment as a specific k8s cluster. Hence to avoid duplicate ourself, we set up a specific repo for github action as `my-action`. When use `my-action` do we need tag it? or we just use `default` branch as it's just internal script.
2.a the benefits for use  `default` branch , is that once there some updates, the changes will auto applied to all other repos invoking `my-action`. (it sounds like bad practice but save effort)
2.b if we use tag, then, the process will be update the code(as 2.a), create a new tag, update tag across the repos invoking `my-action`. are those added steps necessary or any benefits? (it sounds like good practice but adding external effort)

**Comment by SamYuan1990** [comment]
+ Arnaud Le Hors from https://openssf.org/about/tac/ here.
@lehors
I hope you can help us with the case for OpenSSF usage. Here some questions as summary below, if you don't want to go through all the back ground:
1. in a specific program's CI, if they follow up with github action and use some 3rd party action for example `uses: actions/setup-go@v3`, will `actions/setup-go` been a part of SBOM? is there any different from `uses: actions/setup-go@v3`/`uses: actions/setup-go@main` from OpenSSF point of view?

2. for a group of repos, maintainers may found some common part of code which just for CI/CD usage. For example, set up environment as a specific k8s cluster. Hence to avoid duplicate ourself, we set up a specific repo for github action as `my-action`. When use `my-action` do we need tag it? or we just use `default` branch as it's just internal script.
2.a the benefits for use  `default` branch , is that once there some updates, the changes will auto applied to all other repos invoking `my-action`. (it sounds like bad practice but save effort)
2.b if we use tag, then, the process will be update the code(as 2.a), create a new tag, update tag across the repos invoking `my-action`. are those added steps necessary or any benefits? (it sounds like good practice but adding external effort)

something additional
I can understand that as we can recreate the tag.... some one don't want to trust a tag but by using specific git commit hash instead. it's very similar to container image tag. as my though is default branch to latest, git commit hash to image hash id ... tag to tag.
Hence, when we apply/adopted with OpenSSF is there any flexibility as we can benefits from 2.a to save our effort and meet OpenSSF practice at same time?

**Review by bradmccoydev — APPROVED** [review]

**Comment by rootfs** [comment]
@SamYuan1990 the discussion could have been done in a more collaborative way. Tagging or not has merits of its own, let's respect each other priorities before we choose one versus other paths. 

We all want the external tools deliver the consistent UX, using a tagged release of these tools is a step to that goal.

**Comment by SamYuan1990** [comment]
> @SamYuan1990 the discussion could have been done in a more collaborative way. Tagging or not has merits of its own, let's respect each other priorities before we choose one versus other paths.
> 
> We all want the external tools deliver the consistent UX, using a tagged release of these tools is a step to that goal.

thanks @rootfs, @bradmccoydev for your kindness and my apologize for my rude in previous here.
as a retrospect, to better collaborative on our CI pipeline, I created item below on our plan meeting, with short term and long term action. please review and feedback through our planning dashboard offline or planning meeting online.
https://github.com/orgs/sustainable-computing-io/projects/2/views/1?pane=issue&itemId=28750581

**Comment by rootfs** [comment]
Thank you @SamYuan1990! This is great! Let's review this issue next week.

**Pull request merged**
