### PR TITLE
Allow set `DaemonSet` annotations

### PR DESCRIPTION
**Pull request by yellowhat**
Hi,
this PR adds to option to add custom `annotations` to the `DaemonSet`.

Thanks

### CODE REVIEW

**Comment by bradmccoydev** [comment]
LGTM, I have checked this out and tested it with both scenarios and it works with no annotations and annotations.

One question regarding the name 'annotations'. Do we think that these one day could be common annotations that will be used in other manifests or only specific to the daemonset?

If it is only for the daemonset should we call it 'daemonSetAnnotations' instead of 'annotations' to be consistent with the podAnnotations naming already there to be more explicit?

**Comment by yellowhat** [comment]
That is quite difficult question.

I was looking for same examples on the most viewed chart on [artifacthub](https://artifacthub.io/stats).

Some charts divide between a `commonAnnotations` and a separate section for each `deployments`/`statefulset`/..., for example `server.annotations`, but they all have multiple `deployments`/`statefulset`/....

Maybe the closest is [kubernetes-dashboard](https://github.com/kubernetes/dashboard/tree/master/charts/helm-chart/kubernetes-dashboard), they use:
- [`annotations`](https://github.com/kubernetes/dashboard/blob/215d1b3ebdaaf079dae7913a0bbb0a7a33d15212/charts/helm-chart/kubernetes-dashboard/values.yaml#L38) for the `values.yaml`
- [here](https://github.com/kubernetes/dashboard/blob/215d1b3ebdaaf079dae7913a0bbb0a7a33d15212/charts/helm-chart/kubernetes-dashboard/templates/deployment.yaml#L23) is the usage

I am fine either way, I just would like to avoid to overcomplicate things for a future that may never come.

What do you think? @rootfs @bradmccoydev

**Comment by bradmccoydev** [comment]
Agreed, no need to overcomplicate it and it is fine the way you did it. Just thought it was worth bringing up for discussion!

**Review by bradmccoydev — APPROVED** [review]
LGTM

**Pull request merged**
