### PR TITLE
feat: add ArtifactHub Metadata

### PR DESCRIPTION
**Pull request by bradmccoydev**
The Following PR will add the necessary information to enrich the look and feel of the Kepler repo on ArtifactHub. 

Things Changed:
- I have added more metadata to the chart.yaml file which will render in ArtifactHub as per their standard
- Bumped the version of chart to reflect these changes in ArtifactHub
- Added the Artifact badge to the readme of the repo so you can click it
- Added a README.md to the template folder which will render in ArtifactHub for the repo homepage for good experience for users/adopters to see values they can use

### CODE REVIEW

**Comment by yellowhat** [comment]
May I ask why did you create a `README.md` inside the `templates` folder?
You can just append that info the same file in `charts/kepler`.

**Comment by bradmccoydev** [comment]
Hey @yellowhat yes thanks I had it one directory to low, i have added it back up to charts/kepler where it is meant to be..

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
thank you @bradmccoydev

**Comment by bradmccoydev** [comment]
No problem, it is looking really good: https://artifacthub.io/packages/helm/kepler/kepler

**Comment by rootfs** [comment]
very cool! @bradmccoydev

**Pull request merged**
