### PR TITLE
kepler(0.5.3): bump to release-0.6.1

### PR DESCRIPTION
**Pull request by yellowhat**
Bump to release-0.6.1.

Closes https://github.com/sustainable-computing-io/kepler-helm-chart/issues/51

### CODE REVIEW

**Comment by BGrasnick** [comment]
Thank you so much! LGTM! Do you think it makes sense to keep the version numbers in line? So bump the version of this helm chart to 0.6.1 to be in line with kepler itself? I think this could prevent any misunderstandings for users.

**Comment by yellowhat** [comment]
Nope, because if we update the helm side of things the version will drift

**Comment by BGrasnick** [comment]
Yeah makes sense! Nevermind :)

**Comment by yellowhat** [comment]
@BGrasnick  is there someone else that can approve this PR?

**Comment by BGrasnick** [comment]
I am not sure who else can approve and merge PRs but at least @rootfs should be able to do that :)

**Review by jiangphcn — APPROVED** [review]
+1

**Comment by jiangphcn** [comment]
I can do so.

**Pull request merged**
